// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const postExcerpt__title: string;
export const postExcerpt__wrapper: string;
export const postExcerpt__content: string;
export const postExcerpt__date: string;
