version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 10
