title: Bartosz Łaniewski
about:
email: laniewski.bartozzz@gmail.com
# host: 192.168.1.7

url: ""
baseurl: ""
markdown: kramdown

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  load_paths:
    - _sass
    - node_modules
