// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const footer__source: string;
export const footer__item: string;
export const footer: string;
export const footer__menu: string;
export const footer__itemRight: string;
export const footer__itemText: string;
export const footer__itemIcon: string;
export const footer__itemIconYoutube: string;
