// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const toc__list: string;
export const toc__title: string;
export const toc: string;
export const toc__ellipsis: string;
export const toc__link: string;
export const toc__linkActive: string;
