// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const hero: string;
export const hero__wrapper: string;
export const hero__title: string;
export const hero__subtitle: string;
