// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const keyword: string;
export const keyword__outlined: string;
export const keyword__wide: string;
