// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const repository__link: string;
export const repository__name: string;
export const repository__description: string;
export const repository__tag: string;
