// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header__item: string;
export const header: string;
export const dark: string;
export const light: string;
export const header__content: string;
export const header__itemLogo: string;
export const header__itemTogglePlaceholder: string;
