// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const heading__wrapper: string;
export const heading__text: string;
export const heading__textH2: string;
export const heading__textH3: string;
