// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const alert: string;
export const alert__success: string;
export const alert__failure: string;
export const alert__warning: string;
export const alert__info: string;
