// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const game__wrapper: string;
export const game__card: string;
export const game__link: string;
export const game__name: string;
export const game__description: string;
