name: Tests

on:
  push:
    branches:
      - "**"
      - "!master"

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 20

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
