name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: 20

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          publish_dir: ./public
          cname: laniewski.me
